# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm run create-locales
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
